image: node:16.14.2

clone:
  depth: full

pipelines:
  pull-requests:
    '**':
    - step:
        runs-on: 
            - 'self.hosted'
        name: Everything
        script:
        - git checkout $BITBUCKET_PR_DESTINATION_BRANCH
        - git checkout $BITBUCKET_BRANCH
        - DIFFED_FILES_TO_LINT=$(git diff $BITBUCKET_PR_DESTINATION_BRANCH --relative --diff-filter=d --name-only -- "*.ts" "*.tsx" "*.js" "*.jsx")
        - echo $DIFFED_FILES_TO_LINT
        - npm install
        - npx eslint $DIFFED_FILES_TO_LINT
        - npm run-script build:example
