image: node:14.15.1

clone:
  depth: full

pipelines:
  pull-requests:
    '**':

    - step:
        name: Everything public-portal
        script:
        - git checkout $BITBUCKET_PR_DESTINATION_BRANCH
        - git checkout $BITBUCKET_BRANCH
        - cd public-portal
        - DIFFED_FILES_TO_LINT=$(git diff $BITBUCKET_PR_DESTINATION_BRANCH --relative --diff-filter=d --name-only -- "*.ts" "*.tsx" "*.js" "*.jsx")
        - echo $DIFFED_FILES_TO_LINT
        - if [ -z "$DIFFED_FILES_TO_LINT" ]; then exit 0; fi
        - npm install
        - npx eslint $DIFFED_FILES_TO_LINT

    - step:
        name: Everything student-portal
        script:
        - git checkout $BITBUCKET_PR_DESTINATION_BRANCH
        - git checkout $BITBUCKET_BRANCH
        - cd student-portal
        - DIFFED_FILES_TO_LINT=$(git diff $BITBUCKET_PR_DESTINATION_BRANCH --relative --diff-filter=d --name-only -- "*.ts" "*.tsx" "*.js" "*.jsx")
        - echo $DIFFED_FILES_TO_LINT
        - if [ -z "$DIFFED_FILES_TO_LINT" ]; then exit 0; fi
        - npm install
        - npx eslint $DIFFED_FILES_TO_LINT

    - step:
        name: Everything staff-portal
        script:
        - git checkout $BITBUCKET_PR_DESTINATION_BRANCH
        - git checkout $BITBUCKET_BRANCH
        - cd staff-portal
        - DIFFED_FILES_TO_LINT=$(git diff $BITBUCKET_PR_DESTINATION_BRANCH --relative --diff-filter=d --name-only -- "*.ts" "*.tsx" "*.js" "*.jsx")
        - echo $DIFFED_FILES_TO_LINT
        - if [ -z "$DIFFED_FILES_TO_LINT" ]; then exit 0; fi
        - npm install
        - npx eslint $DIFFED_FILES_TO_LINT